### ISSUE TITLE
Properties instead of getters and setters

### ISSUE THREAD

**Issue by jonathan-s** [bear/python-twitter#223]
At the moment the api is modeled after getters and setters. It's a bit cumbersome. I think it would be easier to have it as properties. I realize that that would involve some amount of refactoring. If it would be of interest I might look into how that could be done later.

**Comment by bear** [comment]
That is high on my list todo - would welcome any work that gets us moving in that direction

**Comment by jonathan-s** [comment]
@bear, btw, is there any reason that there are setters and getters to begin with? The properties of a class are exposed nonetheless and it seems like there is no logic in the setters. But perhaps you have plans to implement at some point?

**Comment by jonathan-s** [comment]
I started to do some work on it: https://github.com/jonathan-s/python-twitter/blob/property/twitter/user.py That's how I envision doing it. If that looks good, I'll continue.

**Comment by bear** [comment]
The code was structured this way originally so that it could be generated from the protobuff definition.
I like where your going with this but I'm wondering if we should go further and only define a setter if it is truly required.
Also, I can add you to the committers list so you can work from a branch much easier if you like

**Comment by jonathan-s** [comment]
Are there other things high on your list?

**Comment by bear** [comment]
do another review of the methods to make sure the API is fully covered
