### ISSUE TITLE
VerifyCredentials Error

### ISSUE THREAD

**Issue by EralpB** [bear/python-twitter#235]
>>> print api.VerifyCredentials()
{"id": 16133, "location": "Philadelphia", "name": "bear"}

This is given on Readme, but what if its invalid, does the function raise TwitterError, another error or just return nil?

Thanks.

**Comment by bear** [comment]
The call was removed from the api - the README should be changed.

The best place to test credentials is now on the dev.twitter site

**Comment by jquacinella** [comment]
I might be confused but I do not think its removed from the API. Check: https://dev.twitter.com/rest/reference/get/account/verify_credentials

As a matter of fact, official Twiter developers refer to this API call as the only way of getting a user's email if you have sufficient permissions. Check for a post on Apr 27th by a Twitter dev on this link: https://twittercommunity.com/t/how-to-get-email-is-using-twitter-api-on-callback-page-using-php/404/207

This API should be updated, if anything, with correct parameters.

**Comment by jquacinella** [comment]
Playing with the function, adding data={"include_email": u"true"} to the VerifyCredentials() function does indeed return me an email now that I have correct permissions. I am going to fork this project and see if I can submit a patch (if you would like).

**Comment by bear** [comment]
please do @jquacinella - that would be much appreciated.

thanks for doing the research to answer this!

**Comment by thetylerhayes** [comment]
@jquacinella did you ever fork? would love love love to have `include_email` in this project

**Comment by jmgamboa** [comment]
Hi, im trying to use verify credentials with hellojs. Their token data response is in a weird format. according to this post its https://github.com/MrSwitch/hello.js/issues/253 "clientid-accesstoken:tokensecret@consumerkey" I keep getting twitter.error.TwitterError: [{u'message': u'Invalid or expired token.', u'code': 89}]. even though i just got a fresh set from hellojs

i'm using the credentials directly from the hellojs site https://adodson.com/hello.js/#hellologin page. could it be the issue that because i was authenticating with their app and not my own, granting different permissions?

**Comment by bear** [comment]
I think you may have the wrong python twitter library - or even the wrong js twitter library?

**Comment by jquacinella** [comment]
Oh man, I completely forgot about this. I did make a fork, but that was back on Aug 12, 2015, almost a year ago (https://github.com/jquacinella/python-twitter/commit/1e6b64f4eaa652bd4666f0571ddc8cb76fd90ec3). I assume this was never solved in another ticket, so all I would have to do is update my fork and submit a pull request?

**Comment by bear** [comment]
@jquacinella please do

(apologies for the delay in responding, I was AFK from the internet for the last week)

**Comment by jeremylow** [comment]
Landed in #376. Closing issue.
