### ISSUE TITLE
Python 3 - importError

### ISSUE THREAD

**Issue by fullmogra** [bear/python-twitter#302]
Traceback (most recent call last):
  File "<pyshell#238>", line 1, in <module>
    import twitter
  File "\Python35\lib\site-packages\twitter\__init__.py", line 31, in <module>
    from _file_cache import _FileCache
ImportError: No module named '_file_cache'

OS: Windows 10

**Comment by jeremylow** [comment]
First off, I'm on Linux, but have a virtual machine for Windows. That said, I'm not familiar with Windows development, so this is just my totally naive understanding of how to get things done and not "best practices" or anything like that. Using python3.4 & python3.5, I was able to get python-twitter working as follows.

On a clean install of Windows 8 (sorry - I don't have Windows 10), these are the steps I took. I've split this up into using either Cygwin or the official Python 3.5.1 installer and then the common steps to use python-twitter after that.

#### With Cygwin
1. Install cygwin
2. Install packages for ``python3`` + ``python3-setuptools``
3. Since you'll need pip to install dependencies: download https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
4. Run ``python3 ez_setup.py``
5. Run ``easy_install-3.4 pip``
6. Open up the cygwin terminal.


#### With Python 3.5.1 Official Binaries
1. Install Python 3.5.1 from https://www.python.org/downloads/release/python-351/ using "Add Python 3.5 to PATH"
2. Using the defaults, this install pip so there's no need to go through the other steps above.
3. Open up ``command.exe``


### Common steps
1. Clone master branch of repo (``git clone https://github.com/bear/python-twitter``)
3. ``cd`` into the cloned repository (i.e., for me, it was ``cd C:\cygwin\home\Jeremy\python-twitter``)
2. Run ``pip install -r requirements.txt``
3. Here's the program I'm testing (``test.py``):

    ``` python
import twitter

CONSUMER_KEY = 'www'
CONSUMER_SECRET = 'xxx'
ACCESS_TOKEN = 'yyy'
ACCESS_TOKEN_SECRET = 'zzz'

api = twitter.Api(
    consumer_key=CONSUMER_KEY,
    consumer_secret=CONSUMER_SECRET,
    access_token_key=ACCESS_TOKEN,
    access_token_secret=ACCESS_TOKEN_SECRET)

print(api.VerifyCredentials())
    ```

5. Run that program with ``python3 test.py``

--------

If you have proper access tokens, you should see the output from Twitter. Since your error output above is referencing 
```
\Python35\lib\site-packages\twitter__init__.py
```
I imagine that you've got an old installation of python-twitter lying around somewhere. I'd uninstall that (``pip uninstall python-twitter``) before trying the steps above.

Since you said that you had a workaround with tweepy, I'm going to close this issue. If you try the instructions above and have any troubles, please reopen the issue and I'll see what I missed something.
