### ISSUE TITLE
self.now is None in the `function relative_created_at(self)` in twitter/models.py

### ISSUE THREAD

**Issue by bydeath** [bear/python-twitter#331]
I am using examples/twitter-to-xhtml.py, I used my  `Access Token`. The python-twitter code I used is the latest commit. A TypeError occurs when I run twitter-to-xhtml.py and the tracebook is below. 

> Traceback (most recent call last):
  File "twitter-to-xhtml.py", line 95, in <module>
    main()
  File "twitter-to-xhtml.py", line 91, in main
    FetchTwitter(user, output)
  File "twitter-to-xhtml.py", line 59, in FetchTwitter
    xhtml = TEMPLATE % (s.user.screen_name, s.text, s.user.screen_name, s.id, s.relative_created_at)
  File "../python-twitter/twitter/models.py", line 420, in relative_created_at
    delta = int(self.now) - int(self.created_at_in_seconds)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by jeremylow** [comment]
From the tests, it looks like you should be setting status.now:

https://github.com/bear/python-twitter/blob/master/tests/test_status.py#L53

**Comment by jeremylow** [comment]
I wonder if it makes more sense to remove the `relative_created_at` and `now` @&#8203;properties since that is often more of a front end concern, that is, it's unclear that the end user's timezone is so _"about a second ago"_ for the server could be _"yesterday"_ for me the user, or, if it is not a front-end concern, there are packages that do this kind of thing exclusively, such that we don't reinvent the wheel over here with an abbreviated implementation. 

Javascript:
* https://github.com/moment/moment
(I am not a JS person, so this is really the only one I know of.)

Python:
* https://github.com/bear/parsedatetime 
* https://github.com/jmoiron/humanize
* http://babel.pocoo.org/en/latest/dates.html
* https://github.com/scrapinghub/dateparser

Dedicated packages have the advantage of offering things internationalization, which seem a little out of scope here. @bear since you actually wrote one of those, thoughts?

**Comment by bear** [comment]
yea, doing relative date parsing with timezone awareness is very messy ... *very*

I would be +1 to removing all of that

**Comment by jeremylow** [comment]
Lands in 311c6bf0a97c58173d527f07288b8e9ccb836958
