### ISSUE TITLE
move param_defaults to class - suggestion

### ISSUE THREAD

**Issue by gsmith-to** [bear/python-twitter#424]
This is a suggestion to make a small modification to the `Model` class definitions, which will improve speed and reduce memory usage.

Currently each class based on `TwitterModel` constructs during its `__init__` a dictionary `param_defaults`, which is bound to the instance and which never changes.

The suggestion is to move these out of the `__init__` function (but still within the class definition) -- and  assign to `param_defaults` instead of  `self.param_defaults` --  so that the value becomes a class data variable, and is constructed only once and bound to the class.

Example below for `Media`. No other changes are needed since `self.param_defaults` within a method will find the value in the class. The benefit is that instances will consume less memory and be faster to construct. (The only issue is that any modifications to param_defaults would affect all instances, but it seems clear this is intended to be a read-only element of the data structure).

```
class Media(TwitterModel):

    """A class representing the Media component of a tweet. """
    param_defaults = {
            'display_url': None,
            'expanded_url': None,
            'ext_alt_text': None,
            'id': None,
            'media_url': None,
            'media_url_https': None,
            'sizes': None,
            'type': None,
            'url': None,
            'video_info': None,
        }

    def __init__(self, **kwargs):

        for (param, default) in self.param_defaults.items():
            setattr(self, param, kwargs.get(param, default))

```

**Comment by jeremylow** [comment]
I'm fine with this change, but I don't think it's actually going to make much difference unfortunately. In testing, there's ~100 bytes size difference between the version with the class attributes of `param_defaults` and version with the instance attributes. Using the following program to test each version:

```python
# -*- coding: utf-8 -*-
import pickle
import sys
import twitter

CONSUMER_KEY = 'WWW'
CONSUMER_SECRET = 'XXX'
ACCESS_TOKEN_KEY = 'YYY'
ACCESS_TOKEN_SECRET = 'ZZZ'

if __name__ == '__main__':
    api = twitter.Api(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN_KEY, ACCESS_TOKEN_SECRET)
    tweets = api.GetUserTimeline(count=1000)  # about 89 tweets for my test account
    print(sum([sys.getsizeof(s) for s in tweets]))
    tweets_pickled = [pickle.dumps(s) for s in tweets]
    print(sum([len(s) for s in tweets_pickled]))
```

Class attribute version
```python
4984  # sys.getsizeof
438950  # len of pickled (give or take, varies with each run)
```

Instance attribute version:
```python
4984  # sys.getsizeof
448183  # len of pickled (give or take, varies with each run)
```

In terms of performance, looking at this [article from 2013](https://www.toptal.com/python/python-class-attributes-an-overly-thorough-guide) (on python 2.7.2 admittedly), seems like it's kind of a wash performance-wise. In my testing, the difference is negligible with class variables being very slightly faster for initialization:

```python
# -*- coding: utf-8 -*-
import timeit

if __name__ == '__main__':
    # Instance attribute version
    t = timeit.timeit(
        'twitter.models.Status.NewFromJsonDict(STATUS_SAMPLE_JSON)',
        setup="""import json; import twitter; f = open('testdata/models/models_status.json', 'rb'); STATUS_SAMPLE_JSON = json.loads(f.read().decode('utf8'))""")
    print("Instance attribute initialization: ", t)

    # Class attribute version
    t2 = timeit.timeit(
        'twitter.models.StatusTwo.NewFromJsonDict(STATUS_SAMPLE_JSON)',
        setup="""import json; import twitter; f = open('testdata/models/models_status.json', 'rb'); STATUS_SAMPLE_JSON = json.loads(f.read().decode('utf8'))""")
    print("Class attribute initialization: ", t2)
```

Output:
```python
Instance attribute initialization:  47.60752862901427
Class attribute initialization:  46.76807844999712
```

(The `testdata/models/models_status.json` file referenced is the same one as in the Github repo, so you can run these tests yourself.)

These tests were run only changing the `twitter.models.Status` object, so changing all the twitter models may yield larger gains (since `Status` objects contain `User`, `Url`, `Media`, etc. objects)
