### ISSUE TITLE
Package name is same as the another twitter package called "python twitter tool"

### ISSUE THREAD

**Issue by NestLakerJasonLIN** [bear/python-twitter#557]
This is issue cannot be avoided if someone want to install both of them and make some comparison. For me, both this package and the `python twitter tool` will be installed into the same directory named `twitter`. Then some method like `twitter.Api()` cannot be called due to conflict.

**Comment by jeremylow** [comment]
I'm afraid there's nothing we can really do about that since both packages were created over ten years ago now.

You could create a virtual environment, clone both repos, install both `pip install -e .` after changing the `setup.py` files to reflect different package names. This may cause some breakage however, so you'd need to experiment with your options there. Alternatively, you could create two separate virtual environments and install both packages into their own venvs.
