### ISSUE TITLE
twitter.error.TwitterError: Not authorized

### ISSUE THREAD

**Issue by n2k3bu1** [bear/python-twitter#596]
Hi there,
As I turn on "**[X] Protect your Tweets**" my profile setting at https://twitter.com/settings/safety 
I got an exception error such as **twitter.error.TwitterError: Not authorized** when making a call APIs
Maybe I have a something wrong as request API for twitter?
Thanks,

**Comment by PokestarFan** [comment]
I'm not a contributor but what is your call to the API? You can replace the strings with "null" for privacy. Just show me how you call it.

**Comment by PokestarFan** [comment]
Like for example 
```python
api = twitter.api.Api(consumer_key = "null", consumer_secret = "null", access_token_key = "null", access_token_secret = "null")
```

**Comment by IoIxDButStronger** [comment]
This error means your account is shadowbanned. To confirm it, use https://shadowban.eu/

**Comment by sboulhazaiz** [comment]
> This error means your account is shadowbanned. To confirm, use https://shadowban.eu/.

i don't think it's related

**Comment by sboulhazaiz** [comment]
> This error means your account is shadowbanned. To confirm, use https://shadowban.eu/.

100% wrong.
I checked : I had this error message because i was trying to call this API through "application_only_auth", and while trying with OAuth1.0 instead, it worked.
Some APIs of twitter will work only with application-only authentification, some only with OAuth1.0 and some will work with no problem with both application-only or OAuth1.0
