### ISSUE TITLE
Get tweets from Tweet ID

### ISSUE THREAD

**Issue by Nitrama** [bear/python-twitter#624]
Hello,
is there a way to get all the data from tweets?
So Likes/Retweets/comments?

**Comment by jeremylow** [comment]
Not really in the sense that there's no way to get *all* of those things. You can get the most recent 100 retweets with [GetRetweets](https://python-twitter.readthedocs.io/en/latest/twitter.html#twitter.api.Api.GetRetweets) and you can get replies to a tweet with [GetReplies](https://python-twitter.readthedocs.io/en/latest/twitter.html#twitter.api.Api.GetReplies). Unfortunately, there's no way to get likes of a tweet since Twitter doesn't have an API endpoint for those.
