### ISSUE TITLE
Does it work with v2 of twitter API

### ISSUE THREAD

**Issue by belalhamdy** [bear/python-twitter#699]
I am wondering if this library still works until now with the new version or not

**Comment by MrCsabaToth** [comment]
I want to know as well. I cloned the repo but didn't find any meaningful hit on "v2" pattern search. I'd expect to find it in some py files. Plus the recency (unrecency) of the folders are telling as well, the most recent is like two years old.

**Comment by me-and** [comment]
Currently this library only works with v1.1 of the API. You can check by looking at the below code:

https://github.com/bear/python-twitter/blob/1a148ead5029d06bec58c1cbc879764aa4b2bc74/twitter/api.py#L262-L264

**Comment by sebix** [comment]
Has anyone worked on this issue or knows alternative libraries?

**Comment by akrherz** [comment]
Anybody watching this have updated comments?  Who knows what twitter will do, but it appears most of the 1.1 API is being removed on 29 April 2023 (sans media upload).

**Comment by MrCsabaToth** [comment]
> Anybody watching this have updated comments? Who knows what twitter will do, but it appears most of the 1.1 API is being removed on 29 April 2023 (sans media upload).

I saw Twitter announced impossible pricing tiers completely out of touch with reality, but I missed they'd discontinue v1.1. Thanks for bringing my attention to it. I'm using mixed 1.1 and 2.0 APIs so I need to convert all v1.1 to v2 I guess on top of converting a ton of code to web scraping. I hope Twitter will be hammered and they'll have to backtrack because I really don't want to develop web scraping code.
